services:
  pitico_db:
    image: postgres:17
    env_file:
      - .env    
    # environment:
    #   POSTGRES_DB: ${POSTGRESQL_DATABASE}
    #   POSTGRES_USER: ${POSTGRESQL_USER}
    #   POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:
